# Treefmt Configuration
# One tool to format them all.

[formatter.kotlin]
command = "ktlint"
options = [ "--format" ]
includes = ["*.kt", "*.kts", "**/*.kt", "**/*.kts"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix", "**/*.nix"]
